SELECT mhc_allele_restriction_id as id,
       displayed_restriction as label,
       synonyms,
       includes,
       restriction_level as level,
       organism as taxon_name,
       organism_ncbi_tax_id as taxon_id,
       class,
       haplotype,
       locus,
       serotype,
       molecule,
       chain_i_name as chain_i,
       chain_i_locus,
       chain_i_mutation,
       chain_ii_name as chain_ii,
       chain_ii_locus,
       chain_ii_mutation
 FROM mhc_allele_restriction
